GoalApp/config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:index] do
    resources :goals, only: [:show]
    # member do
    #   post 'comment'
    # end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :goals, except: [:show] do
    # member do
    #   post 'comment'
    # end
  end

  resources :comments, only: [:create, :destroy]

  root "goals#index"
end

GoalApp/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :author_id, :body, :commentable_id, :commentable_type, presence: true

  belongs_to :author, class_name: 'User'

  belongs_to :commentable, polymorphic: true
end

GoalApp/app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable,
      class_name: "Comment",
      dependent: :destroy
  end
end

GoalApp/app/models/goal.rb
class Goal < ActiveRecord::Base
  include Commentable

  validates :title, :body, :user_id, presence: true

  belongs_to :user


end

GoalApp/app/models/user.rb
class User < ActiveRecord::Base
  include Commentable
  
  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  validates :username, :session_token, uniqueness: true

  has_many :goals

  after_initialize :ensure_session_token


  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end


  def self.find_by_credentials(username, password)
    @user = User.find_by_username(username)
    return nil unless @user && @user.is_password?(password)
    @user
  end

  def generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save
    self.session_token
  end

  private
    def ensure_session_token
      self.session_token ||= generate_session_token
    end

end

GoalApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  protected

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

GoalApp/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    params[:comment][:author_id] = current_user.id
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to :back
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to :back
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @comment.commentable
  end


  private
    def comment_params
      params.require(:comment).permit(:body, :author_id, :commentable_id, :commentable_type)
    end
end

GoalApp/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :redirect_if_not_author, only: [:show, :edit, :update, :destroy]

  def index
    @goals = Goal.where(privacy: false)
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = current_user.goals.new(goal_params)

    if @goal.save
      redirect_to user_url(current_user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])

    if @goal.update(goal_params)
      redirect_to user_goal_url(id: @goal.id, user_id: current_user.id)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to user_url(current_user)
  end

  private

    def goal_params
      params.require(:goal).permit(:title, :body, :user_id, :privacy)
    end

    def redirect_if_not_author
      @goal = Goal.find(params[:id])
      redirect_to user_url(current_user) unless @goal.privacy == false || @goal.user_id == current_user.id
    end
end

GoalApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

GoalApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.includes(:goals).find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_url
  end

end

GoalApp/app/helpers/application_helper.rb
module ApplicationHelper
  def include_form_auth_token
    "<input type=\"hidden\" name=\"authenticity_token\" value=\"#{form_authenticity_token}\">".html_safe
  end
end

GoalApp/app/helpers/comments_helper.rb
module CommentsHelper
end

GoalApp/app/helpers/goals_helper.rb
module GoalsHelper
end

GoalApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

GoalApp/app/helpers/users_helper.rb
module UsersHelper
end

GoalApp/app/views/comments/_comment.html.erb
<strong>Comments</strong>

<% commentable_obj.comments.each do |comment| %>
    <div>
      <%= comment.body %>
      <%= link_to comment.author.username, user_url(comment.author) %>
    </div>
<% end %>

GoalApp/app/views/comments/_form.html.erb
<form action="<%= comments_url %>" method="POST">
  <%= include_form_auth_token %>
  <input type='hidden' name='comment[commentable_type]' value='<%= commentable_obj.class %>'>
  <input type='hidden' name='comment[commentable_id]'  value='<%=commentable_obj.id %>'

<div>
  <label>Comment:<br>
    <textarea name="comment[body]"></textarea>
  </label>
</div>

  <br>
  <input type="submit" value="Add Comment">

</form>

GoalApp/app/views/goals/_form.html.erb
<% action_url, form_method = @goal.persisted? ? [goal_url(@goal), :patch] : [goals_url, :post] %>
<% submit_text = @goal.persisted? ? 'Update Goal' : 'Submit Goal' %>

<%= render 'layouts/errors' %>

<form action='<%= action_url %>' method="POST">
  <%= include_form_auth_token %>
  <input type='hidden' name="_method" value='<%= form_method %>'>

<div>
  <label>Title
    <input type='text' name='goal[title]' value='<%= @goal.title %>'>
  </label>
</div>

<div>
  <label> Body
    <textarea name='goal[body]'><%= @goal.body %></textarea>
  </label>
</div>

<div>
  <label>Private?
    <input type="checkbox" name="goal[privacy]" value="true" <%= "selected" if @goal.privacy %>>
  </label>
</div>

  <input type="submit" value="<%= submit_text %>">
</form>

GoalApp/app/views/goals/edit.html.erb
<h1>Edit <%= @goal.title %></h1>

<%= render "form" %>

GoalApp/app/views/goals/index.html.erb
<h1>All Public Goals</h1>

<ul>
  <% @goals.each do |goal| %>
    <li><%= link_to goal.title, goal_url(goal) %></li>
  <% end %>
</ul>

GoalApp/app/views/goals/new.html.erb
<h1>Add a New Goal</h1>

<%= render "form" %>

GoalApp/app/views/goals/show.html.erb
<%= render 'layouts/errors' %>

<h1><%= @goal.title %> Description</h1>

<h4><%= @goal.body %></h4>

<%= render "comments/comment", commentable_obj: @goal %>
<%= render "comments/form", commentable_obj: @goal %>

<%= button_to 'Delete Goal', goal_url(@goal), method: :delete %>
<%= button_to 'Edit Goal', edit_goal_url(@goal), method: :get %>
<%= button_to "Back to #{@goal.user.username}", user_url(@goal.user), method: :get %>

GoalApp/app/views/layouts/_errors.html.erb
<%= flash[:errors].join('<br>').html_safe if flash[:errors] %>

GoalApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if logged_in? %>
  <%= current_user.username %> <%= button_to "Log Out", session_url, method: :delete %>
<% else %>
  <%= link_to "Log In", new_session_url %>
  <%= link_to "Sign Up", new_user_url %>
<% end %>
<%= yield %>

</body>
</html>

GoalApp/app/views/users/_form.html.erb
<% action_url, action_method = @user.persisted? ? [user_url(@user), 'PATCH'] : [users_url, 'POST'] %>
<% submit_text = @user.persisted? ? 'Update User' : 'Create User' %>

<%= render 'layouts/errors' %>

<form action='<%= action_url %>' method="POST">
  <input type='hidden' name='_method' value='<%= action_method %>'>
  <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>' >

  <label>Username:
    <input type='text' name='user[username]'>
  </label>

  <label>Password:
    <input type='password' name='user[password]'>
  </label>

  <input type='submit' value='<%= submit_text %>'>

</form>

GoalApp/app/views/users/new.html.erb
<h1> Create a New User </h1>

<%= render 'form' %>

GoalApp/app/views/users/show.html.erb
<%= render 'layouts/errors' %>
<h1><%= @user.username %> Homepage</h1>

<ul>
  <% @user.goals.each do |goal| %>
    <li>
      <%= link_to goal.title, user_goal_url(id: goal.id, user_id: params[:id]) %>
      <%= button_to 'Delete Goal', goal_url(goal), method: :delete %>
      <%= button_to 'Edit Goal', edit_goal_url(goal), method: :get %>
    </li>

  <% end %>
</ul>

<div>
  <%= link_to "Add Goal", new_goal_url %>
</div>

<%= render "comments/comment", commentable_obj: @user %>
<%= render "comments/form", commentable_obj: @user %>